#spring.application.name=ecomApplicationUdemy
#server.port=8081

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring:
  application:
    name: ecomApplicationUdemy

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_udemy
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

